### ISSUE TITLE
Removal of attestation and attestation authority from Grafeas API

### ISSUE THREAD

**Issue by TheFrogPad** [grafeas/grafeas#104]
## Problem

Using the latest RI server the schema elements `attestationAuthority` for Notes and `attestation` for Occurrences have been removed. Is the change in schema an omission error when the API definition moved to use of Protocol Buffers?

The `kind` enum also does not list these types as well and if these have been removed is there any information that describes the replacement?

When you look at the [Grafeas overview](https://grafeas.io/docs/concepts/what-is-grafeas/overview.html) there is a table listing some of the kinds of metadata and `ATTESTATION` is listed there but I cannot seem to find this `kind` in the [current API](https://github.com/grafeas/grafeas/blob/master/v1alpha1/proto/grafeas.proto). When looking at the previous API defined in Swagger, the `kind` enum did have an `ATTESTATION_AUTHORITY` but I could not find `ATTESTATION` even then and when trying to include these values for the `kind` in a POST body, the server rejects the request with an error.

Also, I noticed that I needed to include the `name` in the Occurrence JSON as an Occurrence ID was not generated as had been done previously. The comments in the API also say `Output only. The name of the `Occurrence` in the form "projects/{project_id}/occurrences/{OCCURRENCE_ID}"` so has something changed around the Occurrence ID handling as in the server will no longer generate an Occurrence ID?

I'm trying to understand how to properly handle attestations and the PGP signing mechanisms used with attestations.

Thanks, -Craig

### Background

When I start the [Grafeas server](https://github.com/grafeas/grafeas/tree/master/samples/server/go-server/api/server) and attempt to post the Note and Occurrence from the [Grafeas tutorial](https://github.com/kelseyhightower/grafeas-tutorial) the JSON is accepted but I do not see the `attestationAuthority` or `attestation` in the response as presumably these elements are not part of the current API definition.

### Examples

Using a Note:
```
% curl -X POST "http://localhost:8080/v1alpha1/projects/image-signing/notes" -d @pgp_note.json
{"name":"projects/image-signing/notes/production","shortDescription":"Production image signer.","longDescription":"Production image signer.","kind":"KIND_UNSPECIFIED","relatedUrl":[],"expirationTime":null,"createTime":null,"updateTime":null}
```
The pgp_note.json is:
```
{
  "name": "projects/image-signing/notes/production",
  "shortDescription": "Production image signer.",
  "longDescription": "Production image signer.",
  "attestationAuthority": {
    "hint": {
      "humanReadableName": "production"
    }
  }
}
```

Using an Occurrence:
```
% curl -X POST "http://localhost:8080/v1alpha1/projects/image-signing/occurrences" -d @pgp_occurrence.json
{"name":"projects/image-signing/occurrences/GUID1","resourceUrl":"https://gcr.io/hightowerlabs/echod@sha256:aba48d60ba4410ec921f9d2e8169236c57660d121f9430dc9758d754eec8f887","noteName":"projects/image-signing/notes/production","kind":"KIND_UNSPECIFIED","remediation":"","createTime":null,"updateTime":null}
```
The pgp_occurrence.json is:
```
{
  "name": "projects/image-signing/occurrences/GUID1",
  "resourceUrl": "https://gcr.io/hightowerlabs/echod@sha256:aba48d60ba4410ec921f9d2e8169236c57660d121f9430dc9758d754eec8f887",
  "noteName": "projects/image-signing/notes/production",
  "attestation": {
    "pgpSignedAttestation": {
       "signature": "LS0tLS1CRUdJTiBQR1AgU0lHTkVEIE1FU1NBR0UtLS0tLQ0KSGFzaDogU0hBMQ0KDQpzaGEyNTY6YWJhNDhkNjBiYTQ0MTBlYzkyMWY5ZDJlODE2OTIzNmM1NzY2MGQxMjFmOTQzMGRjOTc1OGQ3NTRlZWM4Zjg4Nw0KLS0tLS1CRUdJTiBQR1AgU0lHTkFUVVJFLS0tLS0NClZlcnNpb246IEJDUEcgdjEuNTYNCg0KaVFKS0JBRUJBZ0EwQlFKYWM2Z3lMUnhVYUdWR2NtOW5VR0ZrSUNoSGFYUklkV0lwSUR4amNtRnBaeTV3WlhKbA0KZWtCdmNtRmpiR1V1WTI5dFBnQUtDUkR5V1drbjZEeGRmbnJpRUFDcEFnYWhPLzF3Ryt5bkZVMWJhZmhva1hrbw0KTUtaUVdpTks1clpwRmRZNGEwdEhiMDBzTGtlSWpGSUN2emRYK3lnVGlkZ1dYclplYXhVSm1ycXN5VG1sK1gwUA0KTFVVR1JqNGh3b1dMWUZSREY3WjJLUXBoazNDV2lpN3JTNUkzT1B1RmZoMjMvUUE4eFZBa2ExbHdQdkRjSHphag0KUE9FUklINzBPaUtqTWZMM2o0Q0RoN1FEUWM2Z0I5Z2p3Ky9tTHNjN3UvNmhBQ3ZUNkZ5UXRrQStJM28rWk5ETA0KYUlEbGRvKzZVVGJBSUd1dHBlbWlTbDl0Y3Z4S1Q4K1A1djZ6cTUrdjgwYU1uaWs4ZlhXZTU3QTZ5UE9MTTFyVA0KRGdOMnVReExiWFJzSkpKNnhmRkg4d2oycklyYSs3dldwQWpEYTFPRXI1Znp1TlNIZEF1aWZ5aTlFZm4zTXRvbQ0Kb2c2a2Y4RzNrYjhUUmFneTdVTnB5QkFFdUttSWhoUlpYM2xoKzNIQXNOcC9mOUNJWVk5NURubW11N0xCV1AwTw0KVUVDTEdUVHpBQ2k5a3pyNmg5b0M5NXhvUjZvbVJrN3pYbTJVRXRzTkQvUHd3dnRDdldTejZTeERtL1JMUVdYcA0KWk4zR0tOWXZpblI1K0wyL1VwQy9YV3hMWHpENm42SldIdGhpSjErTlpYSjdNdWMzSUZrZEsrOE14NTlrc1pCOA0KWU5pOHh3NmtNMFRCVkRFaXJndFY4c2pQV3VRbjRweXgyMFNIWFM2TzIwV3lKbW9zVmE0TVMxMVE0cTlaSUpBTA0KYUl2anZLUHhwaUJLUzY2Wkk4Wk1HQnhiWEkrbWI4M0JONGN1SG1IaFpGUzhCTzlqMDZSRWs4aEozQ1NqRmNPWQ0KMjl0R3l3NzBNSnF4czI2OENRPT0NCj1VNTE1DQotLS0tLUVORCBQR1AgU0lHTkFUVVJFLS0tLS0NCg==",
       "contentType": "application/vnd.gcr.image.url.v1",
       "pgpKeyId": "E83C5D7E"
    }
  }
}
```

**Comment by TheFrogPad** [comment]
BTW, I just realized that the [swagger definition](https://github.com/grafeas/grafeas/blob/master/v1alpha1/proto/grafeas.swagger.json) does not have the `attestationAuthority` or `attestation` but in the [proto](https://github.com/grafeas/grafeas/blob/master/v1alpha1/proto/grafeas.proto) I do see messages for these types.

I'm more familiar with swagger and was assuming the protocol buffers lined up with the generated swagger file so I'm not sure why the discrepancy?

It also appears the schema has changed in some way from the JSON I have examples for, so any help on what's up here would be appreciated.

Thanks, -Craig

**Comment by R2wenD2** [comment]
Hi Craig,

Attestation is still a part of the API, it seems like it was dropped from the generated swagger for some reason. I should have some time later tonight or tomorrow morning to regenerate the json and debug the issues

**Comment by TheFrogPad** [comment]
Hi Wendy, thanks for looking at what is going on with the attestation types...

Do you by chance have some references around signature handling? From the [proto](https://github.com/grafeas/grafeas/blob/master/v1alpha1/proto/grafeas.proto) there is a `PgpSignedAttestation` and there is also a `BuildSignature` which appear to have some different semantics from the comments. Or should I ask about these elements in the [Grafeas Users](https://groups.google.com/forum/#!forum/grafeas-users) Google  group?

Thanks, -Craig

**Comment by R2wenD2** [comment]
The messages here: https://github.com/grafeas/grafeas/blob/master/v1alpha1/proto/grafeas.proto should describe the expectations for the fields. Please let me know if you still have questions.

**Comment by TheFrogPad** [comment]
Sounds good. I also posted a question in the [Grafeas Users](https://groups.google.com/forum/#!forum/grafeas-users) group yesterday about signature handling to see if there would be any comment or remarks. Thanks.

**Comment by R2wenD2** [comment]
Some of the relevant fields for attestations were actually missing from protos. https://github.com/grafeas/grafeas/pull/109 should resolve the missing fields from the generated swagger.

**Comment by R2wenD2** [comment]
#109 is merged, so both the swagger file and protos should container the proper fields. Please reopen if you still see issues.

**Comment by TheFrogPad** [comment]
Thanks, will do.
