### ISSUE TITLE
Bad URL on api/server/README.md

### ISSUE THREAD

**Issue by CameronLonsdale** [grafeas/grafeas#122]
The link "This is a reference implementation of the Grafeas API Spec" (https://github.com/Grafeas/Grafeas/blob/master/README) is not found. This link can be found on the following document: https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/README.md

Apologies for not submitting a pull request to fix the issue, I am too unfamiliar with the project, but hope to soon be more familiar :)

**Comment by furuholm** [comment]
Thanks for reporting this. Pull request #123 fixes this...
