### ISSUE TITLE
Integration with Helm?

### ISSUE THREAD

**Issue by jonahbenton** [grafeas/grafeas#131]
Hi all, are there thoughts for how grafeas and helm would interact? Is a specific helm release of a specific version of a chart a Deployment Kind occurrence? Does helm get its own Kind? 

Thanks,

Jonah

**Comment by vtsao** [comment]
Hi there, for questions like these, we have a mailing list. Could you post to that instead?
https://groups.google.com/forum/#!forum/grafeas-users

Thanks,
Vincent
