### ISSUE TITLE
Querying for outdated images in a cluster?

### ISSUE THREAD

**Issue by jonahbenton** [grafeas/grafeas#132]
Hi, 

I'm curious for the state of thinking of grafeas' intended role in a common situation- a cluster operator wants to know at a particular point in time what images running in the cluster/namespace are out of date. The cluster or namespace equivalent to apt list --upgradable. Is it intended that this question be answerable with grafeas?

**Comment by vtsao** [comment]
Hi there, for questions like these, we have a mailing list. Could you post to that instead?
https://groups.google.com/forum/#!forum/grafeas-users

Thanks,
Vincent
