### ISSUE TITLE
occurrence IDs should be generated by the API

### ISSUE THREAD

**Issue by vtsao** [grafeas/grafeas#157]
In our reference impl of the v1alpha1 Grafeas API, we currently require the occurrence name to be set in CreateOccurrence:
https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/v1alpha1/impl.go#L101

Occurrence names are output only and their IDs should be generated by the API:
https://github.com/grafeas/grafeas/blob/master/v1alpha1/proto/grafeas.proto#L774

Note this is unlike notes, which you need to set the ID for when creating.

This should be fixed in the v1alpha1 ref impl, or it can wait until we update the ref impl to v1beta1.

**Comment by vtsao** [comment]
FYI @shrajfr12

**Comment by vtsao** [comment]
Dan assigning to you for now. This will go hand in hand with the Go client lib sample revamp.

**Comment by DanSanche** [comment]
I'll take a look. Do we want the server to reject any occurrences with assigned names (to give the user feedback), or should it just silently assign and use its own names?

**Comment by DanSanche** [comment]
I'm addressing this here: https://github.com/grafeas/grafeas/pull/160

**Comment by aysylu** [comment]
#160 appears to have addressed the issue. Is there anything else?

**Comment by vtsao** [comment]
#160 did this in the v1alpha1 API layer. This needs to be done in the storage layer, so there is still work here.

**Comment by aysylu** [comment]
I'll take this for the server implementation that uses v1beta1 API.
