### ISSUE TITLE
Provide Issue Templates

### ISSUE THREAD

**Issue by jonpulsifer** [grafeas/grafeas#167]
Should we provide issue templates to allow easier onboarding? Ref https://github.com/grafeas/grafeas/issues/164#issuecomment-399422962

e.g. 
- feature request / proposal
- bug
- general questions

**Comment by aysylu** [comment]
#231 will address the first two bullet points. For general questions, [grafeas-users](https://groups.google.com/forum/#!forum/grafeas-users) is best. I'm in the process of updating the community guidelines to reflect this.

**Comment by aysylu** [comment]
https://github.com/grafeas/grafeas#support now has the information on communication channels.
