### ISSUE TITLE
Occurrence time fields are not set

### ISSUE THREAD

**Issue by weeezes** [grafeas/grafeas#247]
## Expected Behavior

Occurrence `GetCreateTime()` and `GetUpdateTime()` should return the creation time and update times respectively for the given occurrence.

## Actual Behavior

GetCreateTime() and GetUpdateTime() both return `nil`. Tested not to work with psql and memstore backends.

Seems like the field is never set here: 

https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/v1alpha1/impl.go#L327

Or here:

https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/v1alpha1/impl.go#L214

It would be stored without changes to atleast memstore and psql stores (eg. https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/storage/pgsqlstore.go#L181 ).

**Comment by vtsao** [comment]
Thanks for reporting this. This should be set by the storage layer to the database commit time after the row has been inserted. Somewhere here:
https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/storage/pgsqlstore.go#L170

We should do this when we update the storage layer to work with the v1beta1 impl FYI @aysylu.
