### ISSUE TITLE
Ensure `go vet` works with the current Grafeas setup and add it back

### ISSUE THREAD

**Issue by aysylu** [grafeas/grafeas#310]
**Is your feature request related to a problem? Please describe.**
Currently, `vet` command in the `Makefile` fails due to the missing files that are generated by the `build` command:

```go/v1beta1/project/project.go:23:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/project_go_proto
Makefile:37: recipe for target 'vet' failed
make: *** [vet] Error 1
aysylu@aysylu:~/go/src/github.com/grafeas/grafeas$ make
go/v1beta1/api/validators/build/build.go:24:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/build_go_proto
go/v1beta1/api/validators/deployment/deployment.go:23:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/deployment_go_proto
go/v1beta1/api/validators/discovery/discovery.go:24:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/discovery_go_proto
go/v1beta1/api/validators/package/package.go:23:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/package_go_proto
go/v1beta1/api/validators/provenance/provenance.go:23:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/provenance_go_proto
go/v1beta1/project/project.go:23:2: no Go files in /usr/local/google/home/aysylu/go/src/github.com/grafeas/grafeas/proto/v1beta1/project_go_proto
Makefile:37: recipe for target 'vet' failed
make: *** [vet] Error 1
```

There were several other incompatibility issues discovered in the Grafeas codebase with `go vet` that haven't yet been addressed.

**Describe the solution you'd like**
Ensure all issues detected by `go vet` are fixed in the Grafeas codebase, and re-enable `vet` in the Makefile: `build: vet fmt go_protos swagger_docs`.

**Describe alternatives you've considered**
For now, the `vet` command is disabled in the `build` command.

**Additional context**
The issue is also reported in https://github.com/grafeas/grafeas/issues/308

**Comment by aysylu** [comment]
I've run into other issues with `vet`, which is why we have `-composites=false` in the `Makefile`. I think it's best to re-enable this after a more thorough investigation into incompatibility.

**Comment by rxbchen** [comment]
Hi, I'm interested in looking into this issue. Can I get some context into this issue?

**Comment by aysylu** [comment]
Hi @rxbchen, great to hear about your interest! This was filed, because when running `make vet` or `go vet` it'd fail with `composite literal uses unkeyed fields`. The first step would be to remove the flag overwrite and see if it's still failing, given the recent changes to the codebase.

**Comment by rxbchen** [comment]
Hey @aysylu I have `make vet` on macOS and a vagrant ubuntu image, it seems like it's working for me.

**Comment by aysylu** [comment]
@rxbchen great! In that case, could you send a PR that removes this flag? Thanks.

**Comment by rxbchen** [comment]
@aysylu my bad, once I set `-composites=true` it breaks again :/ (I forgot to test that case)

I will continue to look into the issue and look for a fix.

**Comment by aysylu** [comment]
@rxbchen sounds good, thank you!

**Comment by aysylu** [comment]
Thanks, @rxbchen, for fixing this!
