### ISSUE TITLE
Unable to pull docker container

### ISSUE THREAD

**Issue by kellyp** [grafeas/grafeas#363]
## Expected Behavior

```
docker pull us.gcr.io/grafeas/grafeas-server:0.1.0
```

pulls down an image

## Actual Behavior
Links to the relevant code, snippets

```
docker pull us.gcr.io/grafeas/grafeas-server:0.1.0
Error response from daemon: manifest for us.gcr.io/grafeas/grafeas-server:0.1.0 not found: manifest unknown: Failed to fetch "0.1.0" from request "/v2/grafeas/grafeas-server/manifests/0.1.0".
```

## Steps to Reproduce the Problem

Environment, commands

1.  `docker pull us.gcr.io/grafeas/grafeas-server:0.1.0`
 

## Additional info
Add any other context about the problem here (e.g. screenshots, links)

**Comment by aysylu** [comment]
Hi @kellyp, thanks for reporting the issue! The image name is actually `us.gcr.io/grafeas/grafeas-server:v0.1.0`, with **v**0.1.0. We might have forgotten to update documentation somewhere, could you please point me to where this is still out-of-date? Thanks!

**Comment by kellyp** [comment]
hey @aysylu no problem I am now glad I don't have to maintain a copy of the image!  Its in the run it locally docs here: https://github.com/grafeas/grafeas/blob/master/docs/running_grafeas.md#using-published-docker-image

**Comment by aysylu** [comment]
@kellyp thanks for your quick response! #365 should fix this.

**Comment by ljy020516** [comment]
Excuse me, I have the same problem, but I did use it v0.1.0,Is there a new version now？

**Comment by ljy020516** [comment]
@kellyp @aysylu

**Comment by ljy020516** [comment]
@aysylu has it changed to v0.2.0?

**Comment by ljy020516** [comment]
@aysylu has it changed to v0.2.0 already?

**Comment by aysylu** [comment]
@wkozlik: could you please help? I'm no longer a maintainer, @ljy020516

**Comment by wkozlik** [comment]
v0.2.1 is available now.
