### ISSUE TITLE
Add CRUD for projectIds to the api

### ISSUE THREAD

**Issue by R2wenD2** [grafeas/grafeas#40]

**Comment by furuholm** [comment]
Should it be possible to create notes/occurrences for projects that doesn't already exist?

**Comment by R2wenD2** [comment]
It should not, the Grafeas storage layer should check for existence of project prior to creating a note/occurrence. This can be handled using a projects db table (which is probably the easiest way to do this for the reference implementation).

**Comment by furuholm** [comment]
Db table? But there is no database in the reference implementation at this point. Right?

**Comment by R2wenD2** [comment]
I'm using the term database loosely :) We should have a separate map for projects in the storage layer.

**Comment by furuholm** [comment]
That is quite loose 😄

A map we can do. How about a map[string]bool to emulate a set (as we don't have anything but projectId which would then be the key)?

**Comment by furuholm** [comment]
I have implemented the storage layer (https://github.com/furuholm/Grafeas/tree/project-crud). I guess that there is not much more to do before #50 has been completed?

**Comment by furuholm** [comment]
@R2wenD2 I have rebased my project-crud branch on top of https://github.com/Grafeas/Grafeas/pull/79 (https://github.com/combient/Grafeas/tree/project-crud). Will look at the API next. What steps are involved in generating the code?

**Comment by furuholm** [comment]
@R2wenD2 I have implemented the API as well. I guess you prefer a PR once you have merged https://github.com/Grafeas/Grafeas/pull/79 into master?

**Comment by R2wenD2** [comment]
@furuholm a PR once #79 is merged would be great :) After we get them both in I'll regen the client libs.

**Comment by R2wenD2** [comment]
@furuholm I believe this is done now - is anything remaining?

**Comment by furuholm** [comment]
It's done so you can close this issue.
