### ISSUE TITLE
Support Oracle 11g as storage backend

### ISSUE THREAD

**Issue by judavi** [grafeas/grafeas#403]
Hello @aysylu  @vtsao !
I'm not sure how to propose this change so I decided to go with an issue in the repo.
I completed an implementation of Grafeas using Oracle 11G as the storage backend [grafeas-oracle](https://github.com/judavi/grafeas-oracle)
What do you prefer for these custom implementations? I'm cool moving my repo under Grafeas or adding a link from the principal project. What do you think?
Thanks!

**Comment by aysylu** [comment]
Hi @judavi,

That's really cool to hear about the integration of Grafeas with Oracle 11G -- congrats! Let's add the link in the README -- could you please a PR when you get a chance for this? Thanks!
