### ISSUE TITLE
Thoughts on splitting Grafeas service into separate Occurrence and Notes service respectively?

### ISSUE THREAD

**Issue by tianzhou** [grafeas/grafeas#417]
The current GrafeasV1Beta1 is a monolithic service containing both Occurrence and Notes.

Since the comments already suggested "A note contains details describing the analysis and is generally stored in a separate project"

I am wondering if it makes sense to separate Occurrence/Notes on the service level as well?

**Comment by ooq** [comment]
hi @tianzhou, can you provide more analysis on the benefits of such separation or if there are use cases that require so?
Haven't thought deep into the issue, but it's hard for me to think cases when users need to compose them from different services.

**Comment by tianzhou** [comment]
It's about the separation of concerns. e.g. It could be easier to apply different ACLs if they are in separate services. Also the Occurrence and Notes service serves different purposes, e.g. occurrence service might be relatively more critical since the deployment service needs to consult it, and it will be called much more than Notes service

**Comment by ooq** [comment]
Fundamentally, the key data structure design here is a note maps to multiple occurrences. I'm not really convinced here that an occurrence service can be easily separated without duplicating the metadata on its corresponding notes. A separation might make requests to specific occurrences faster, but it would also degrade many other type of requests.

@aysylu who knows more about the history and internals of Notes and Occurrences.

**Comment by aysylu** [comment]
Hi @tianzhou,

Thanks for reaching out, Grafeas Eng Lead here. The design of Grafeas API dictates that occurrences are closely tied with the notes to which they refer. @ooq is correct in that splitting the service to handle notes and occurrences separately has unclear benefits here. Is there a specific use case you're considering Grafeas for that'd be improved by having separate services?

**Comment by aysylu** [comment]
Closing this for now, as this has been addressed. Please feel free to re-open if new information comes up.
