### ISSUE TITLE
I somehow get "Failed to paginate projects" just by curling my grafeas Projects

### ISSUE THREAD

**Issue by stubifox** [grafeas/grafeas#418]
## Expected Behavior
listing of projects
## Actual Behavior
{
  "error": "Failed to paginate projects",
  "message": "Failed to paginate projects",
  "code": 13,
  "details": []
}

## Steps to Reproduce the Problem
curling the projects.
Odd is that somehow if I'm curling a specific project the error is gone and i can look up notes of the project. When i want to have the occurrences of given project, the error occurs again.

I'm running grafeas with Pgsql on Kubernetes

1.  just a simple curl to grafeas .../projects

## Additional info
I didn't do anything special. Just testing out a bit and creating notes and occurrences in a example project just using curl.
I'm pretty sure it is a DB-Issue, but don't know how to fix this without resetting the DB.

**Comment by wkozlik** [comment]
A way around this error is to specify the value for `paginationkey` in the `config.yaml` file. For example:
```
paginationkey: "nhdR6G9RQ3bf5K28Rd5HFq2Qz4RJVuvbqQDLQjs75dA="
```
