### ISSUE TITLE
Unable to generate a note via curl

### ISSUE THREAD

**Issue by greendinosaur** [grafeas/grafeas#422]
## Expected Behavior
Be able to create a note in a project via curl

## Actual Behavior
when I use the below curl command
`curl http://localhost:8080/v1beta1/projects/provider_example/notes?note_id=testNote \
    -X POST -H "Content-Type: application/json" -d @note.json`

I get an error message 
` no matches found: http://localhost:8080/v1beta1/projects/provider_example/notes?note_id=testNote`

I'm able to use curl to create projects successfully prior to this. I've also been able to use the [example grpc client](https://github.com/grafeas/grafeas/blob/master/go/v1beta1/example/client/client.go) to create projects and notes. Seems to be a problem with the REST API.

## Steps to Reproduce the Problem
I'm following the information in the docs about  [creating notes and occurences](https://github.com/grafeas/grafeas/blob/master/docs/create_notes_occurrences.md) 

I'm running v1beta1 grafeas and running the server directly via `go run main/main.go`

If I remove the query string parameter and run 
` curl http://localhost:8080/v1beta1/projects/provider_example/notes \                 
    -X POST -H "Content-Type: application/json" -d @note.json`
then I get 
`{"error":"a noteId must be specified","message":"a noteId must be specified","code":3,"details":[]}`

I can only assume the gateway is not matching the request correctly which is why I get the first error message. I've checked the swagger file and there is no reference to a query string parameter.

**Comment by skelterjohn** [comment]
Can you share the contents of your note?

**Comment by aysylu** [comment]
Hi @greendinosaur,

Thanks for filing the issue. Grafeas Eng Lead here. Could you please share what `note.json` looks like? Note ID is the name of the note, which is a required field: [proto definition](https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/grafeas.proto#L476).

**Comment by greendinosaur** [comment]
Thanks for responding so quickly @skelterjohn and @aysylu . It's the same note as outlined in the [docs](https://github.com/grafeas/grafeas/blob/master/docs/create_notes_occurrences.md)



```json
{
    "name" : "projects/provider_example/notes/test",
    "shortDescription": "A brief description of the note",
    "longDescription": "A longer description of the note",
    "kind": "VULNERABILITY",
    "vulnerability": {
        "details": [
        {
            "package": "libexempi3",
            "cpeUri": "cpe:/o:debian:debian_linux:7",
            "minAffectedVersion": {
              "name": "2.5.7",
              "revision": "1",
              "kind": "NORMAL"
            }
        }]
    }
}
```

**Comment by aysylu** [comment]
Interesting. @wkozlik could you please take a look?

**Comment by wkozlik** [comment]
Hi @greendinosaur, I've been trying to reproduce the problem you encountered. When you run a curl command do you type it in in a single line:
```
curl http://localhost:8080/v1beta1/projects/provider_example/notes?note_id=testNote \ -X POST -H "Content-Type: application/json" -d @note.json
```
or you hit \<ENTER\> after the line continuation character "\\":
```
curl http://localhost:8080/v1beta1/projects/provider_example/notes?note_id=testNote \<ENTER>
> -X POST -H "Content-Type: application/json" -d @note.json
```

**Comment by greendinosaur** [comment]
Thanks for continuing to look into this. I've been keying it into a single line without the continuation character. I still get the error.

Curiously, if I use Postman to POST the data then it works absolutely fine and I can create notes with no problems. Maybe I will just stick to that for learning the API.

I am using a Mac with the latest OS and the Z shell.

**Comment by wkozlik** [comment]
I believe this error is generated by the Z shell. See more details here: https://github.com/ohmyzsh/ohmyzsh/issues/31

The easiest way to get around this error is to wrap the URL with double quotes.

**Comment by greendinosaur** [comment]
Ah, excellent that has fixed the issue. Many thanks for looking into this and recommending an approach. I will close this issue.

**Comment by greendinosaur** [comment]
Problem with z shell. Double quotes around the URL solves it.
