### ISSUE TITLE
type is required: error when creating a Deployment Note

### ISSUE THREAD

**Issue by jacace** [grafeas/grafeas#423]
Hello,

I am trying to create a Deployment Note with the JSON below but I keep getting the error: _{"error":"note is invalid: [type is required]","message":"note is invalid: [type is required]","code":3,"details":[]}_

{
  "ShortDescription": "testdeploy",
  "LongDescription": null,
  "RelatedUrl": [
    {
      "Url": "https://jacace.wordpress.com/",
      "Label": "testurl"
    }
  ],
  "RelatedNoteNames": [
    "https://jacace.wordpress.com/"
  ],
  "Type": {
    "Deployable": {
      "ResourceUri": [
        "https://jacace.wordpress.com/"
      ]
    }
  }
}

I tried with: Type Deployment, Type Deployable, Details, etc but none worked.

Can anyone please provide a working JSON to create a deployment Note?

Thanks,

Javier Caceres

**Comment by greendinosaur** [comment]
I'm having a few problems myself with notes and curl so am struggling to test this out for you. However, I have some pointers which may help.

I've used the below JSON to successfully create a deployment occurrence via this curl command.
curl http://localhost:8080/v1beta1/projects/myproject/occurrences \
     -X POST -H "Content-Type: application/json" -d @occurrence.json

```
{
    "resource": {
      "uri": "https://gcr.io/project/image@sha256:foo"
    },
    "note_name": "projects/myproject/notes/mynote2",
    "kind": "DEPLOYMENT",
    "deployment": {
        "deployment":{
            "user_email": "user_email",
            "address": "address",
            "resource_uri":[
                "resource_uri",
                "resource_uri"
            ],
            "undeploy_time": "2000-01-23T04:56:07.000+00:00",
            "deploy_time": "2000-01-23T04:56:07.000+00:00",
            "config": "config",
            "platform": "CUSTOM"
        }
    }
}
```

Looking at what a note requires, I suspect you need to add the kind attribute and set this to DEPLOYMENT. Rather than using the type attribute, you should just call it deployable and then nest in the deployable object with the resourceuri as you've shown.

Maybe the below would work but I've not been able to test I'm afraid.
```
{
    "shortDescription": "A brief description of the note",
    "longDescription": "A longer description of the note",
    "kind": "DEPLOYMENT",
    "deployable": {
        "deployable": {
            "resource_uri":[
            "resource_uri",
            "resource_uri"
            ]
        }
    }
}
```

**Comment by jacace** [comment]
Hello @greendinosaur 
 
I just tried this and got a different error: "{"error":"note is invalid: [deplyable.resource_uri is required]","message":"note is invalid: [deplyable.resource_uri is required]","code":3,"details":[]}"
 
FYI: I also changed deployable to **deplyable** without luck.
 
{
  "ShortDescription": "testdeploy",
  "LongDescription": null,
  "RelatedUrl": [
    {
      "Url": "https://jacace.wordpress.com/",
      "Label": "testurl"
    }
  ],
  "RelatedNoteNames": [
    "https://jacace.wordpress.com/"
  ],
  "kind": "DEPLOYMENT",
  "deployable": {
    "deployable": {
      "resource_uri": [
        "https://jacace.wordpress.com/"
      ]
    }
  }
}

**Comment by greendinosaur** [comment]
Aha, try this. It is working for me.
```
{
    "shortDescription": "A brief description of the note",
    "longDescription": "A longer description of the note",
    "kind": "DEPLOYMENT",
    "deployable": {        
            "resource_uri":[
            "someurui"
            ]
    }
}
```

**Comment by jacace** [comment]
It works now, thanks @greendinosaur

**Comment by aysylu** [comment]
Hi @jacace and @greendinosaur,

@greendinosaur thanks for your help here! If either of you would like to add some documentation to help others in the future with the example of deployment metadata kind, your contributions are welcome!

Thanks,
Aysylu

**Comment by greendinosaur** [comment]
hey @jacace sounds like you should log a bug about the error message containing a typo. That is confusing. Glad it works now.

@aysylu - would a working postman file do? I've been using postman to generate the API calls to generate both notes and occurrences and I can submit the script along with some commentary.

**Comment by aysylu** [comment]
@greendinosaur: I'm not familiar with postman. Could you please share it here? I suspect it'd be very helpful, just want to make sure I can give a good recommendation for the PR, to make the review smoother.:)

**Comment by greendinosaur** [comment]
Sure, Postman is a free [tool](https://www.postman.com/) that makes it easy to call REST APIs. It's reasonably well known. You can save out your script and store it in a code repository so others can run it. It makes it easy to see the API calls and the JSON that needs to be sent / is received back.

It's probably a supplement to updated documentation with more accurate curl commands and usage of the grafeas client to cover all the diffferent note and occurrences. It would allow people to try out grafeas using whichever method they're most comfortable with (Postman, curl, code) so arguably would lower the barrier to adoption.

**Comment by aysylu** [comment]
@greendinosaur: Awesome, thank you! Yes, we would love your contribution on this.:)
