### ISSUE TITLE
Poison commit leveraging Grafeas

### ISSUE THREAD

**Issue by tianzhou** [grafeas/grafeas#435]
**Is your feature request related to a problem? Please describe.**
Say there occur a bad commit and the commit fixing that issue is later applied. We would like to have a mechanism to ship the package containing both commits or neither of them.

To achieve this, we can flag the initial bad commit as "Poison" and the corresponding fix as "Antidote"

**Describe the solution you'd like**
Integrate the "poison/antidote commit" into one of the existing notes or a new note, and be used as part of the binary authorization process.

**Comment by wkozlik** [comment]
Hi @tianzhou, I suggest you post your question in https://github.com/grafeas/kritis since it is about binary authorization.

**Comment by tianzhou** [comment]
Hi @wkozlik, thanks for the reply. It doesn't hurt to post there as well. Meanwhile, I do like to get some thought from the grafeas group as well since its feasibility depends on whether it makes sense to leverage grafeas data model.

**Comment by liuplgtm** [comment]
hi @tianzhou , the proposal sounds realistic. 
The proposal can be further generalized as an 'atomic group': {commit1, commit2, ... commitN}, which are either all included or all excluded. 

This also means we need to touch multiple parts vertically in the grafeas/kritis stack.
Will keep this proposal in mind. 

any interest in taking a stab at the implementation on your side? :)

**Comment by th3w4y** [comment]
@tianzhou do you mean something like this:

check the fileHashes inside the sourceProvenance...  and look-up against some other attestation that tracks the poisonous commit and fileHash relation... ? 

what  were  your inital thoughts on this?

**Comment by tianzhou** [comment]
@liuplgtm we do occasionally find already identified problematic commits escaped into production. e.g. when the release engineers cut the release at the wrong commits which doesn't include the fix. We'd like to have a mechanism to flag bad commits. The atomic commits concept seems to be sane.

**Comment by tianzhou** [comment]
@th3w4y I will take a look at your pointers. Thanks~

**Comment by liuplgtm** [comment]
what @th3w4y described sounds feasible.

Basically you require the 'non_poisonous' attestation in the authorization stage.
Just make sure the release engineers generate such attestation for only the commits that are not poisonous.  The generation can be done automatically and can be part of your client logic.
