### ISSUE TITLE
[Question] process to contribute a new storage implementation

### ISSUE THREAD

**Issue by maditya** [grafeas/grafeas#491]
Hi,
Is there a process to contribute a new storage implementation for grafeas. We are working on AWS RDS backend and were wondering how to proceed. https://github.com/grafeas/grafeas/issues/341 states that it would be a separate project(repo?). Would the repo eventually be part of grafeas org or managed separately?

@aysylu @wkozlik

**Comment by wkozlik** [comment]
I think it makes sense to start as a separate repo so you have more freedom over the changes you want to make. You can follow https://github.com/grafeas/grafeas/pull/475 as an example of contributing a new backend.

**Comment by maditya** [comment]
awesome, thanks!
