### ISSUE TITLE
Update Note and Occurrence Protos to support SBOM (SPDX) data

### ISSUE THREAD

**Issue by alowayed** [grafeas/grafeas#500]
**Is your feature request related to a problem? Please describe.**
Software is being built and deployed in a way that does not provide visibility in between the source and what’s actually running. 

**Describe the solution you'd like**
Add [SBOM](https://www.ntia.gov/SBOM) support to Grafeas by creating new [SPDS](https://spdx.github.io/spdx-spec/) note and occurrence type protos.

**Describe alternatives you've considered**
Reusing existing notes and occurrence types which do not contain the fields needed to reconstruct SBOM of other formats, such as SPDX.

**Additional context**
This is an early step in supporting SBOM storage in Grafeas and it's translation to and from other formats. It has been a topic of discussion with @aysylu and @wkozlik which may have more designs or documents with more details.

**Comment by aysylu** [comment]
Looking forward to this!
