### ISSUE TITLE
Support git as one of the producers when sending data to Grafeas

### ISSUE THREAD

**Issue by hkadakia** [grafeas/grafeas#516]
In order to have a complete chain of custody, adding support for Git as one of the producers would be ideal. In order to capture git push events, we would ideally need a protobuf which matches the payload published by the git webhook mentioned [here](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#push)

Please let me know if this proposal makes sense and if there is interest around this and I can raise a PR to merge our downstream changes to the Grafeas project.

Thanks for taking a look.

**Comment by aysylu** [comment]
Hi @hkadakia,

Could you please elaborate on how you'd use Git webhook as software supply chain metadata? The way I understand it is, the webhook itself could call Grafeas API to create metadata when it's triggered. Did you have something different in mind?

Thanks,
Aysylu
