### ISSUE TITLE
Updating repeated fields is broken due to grpc-gateway bug

### ISSUE THREAD

**Issue by aethanol** [grafeas/grafeas#522]
## Background
Grafeas is impact by this bug: https://github.com/grpc-ecosystem/grpc-gateway/pull/1921, which was released in [2.3.0](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.3.0), but grafeas is on [2.0.1](https://github.com/grafeas/grafeas/blob/master/go.mod#L17)

## Expected Behavior
Updating an occurrence should allow for a list of repeated fields to be appended to the existing fields.

## Actual Behavior
Updating an occurrence returns an error if you update a repeated field.

```
{\"code\":3,\"message\":\"only one repeated value is allowed per field_mask\"}: 400 Bad Request"
```

**Comment by aysylu** [comment]
@aethanol thanks for reporting this issue! if you'd like to create a PR to fix this, your contribution is very welcome!
