### ISSUE TITLE
Use Grafeas v1 API

### ISSUE THREAD

**Issue by chuangw6** [grafeas/grafeas#538]
**Is your feature request related to a problem? Please describe.**
Hi team,
We want to use Grafeas v1 API in our open source project (tekton chains) but it seems not available on pkg.go.dev. 

**Describe the solution you'd like**
We notice that `proto/v1/*_go_proto/` is [ignored](https://github.com/grafeas/grafeas/blob/d50efcd47604b2d35e7d6def168c9949304ca019/.gitignore#L9) in the .gitignore file. Can we remove that so that pkg.go.dev is able to pick it up?

**Describe alternatives you've considered**
If not, what is the best way to import it in a project?

Thanks!

**Comment by alowayed** [comment]
Hey @chuangw6 ,

Seems you're right. #540 should fix this and introduce the go protos you need. This will be auto-closed once it's merged.
