### ISSUE TITLE
Avoid using unicode punctuations in schema docs

### ISSUE THREAD

**Issue by pombredanne** [Grafeas/Grafeas#55]
This is minor but a possible source of inconveniences in the future: see https://github.com/Grafeas/Grafeas/blob/dda9654a580daec8c8ec7e16eed67589e2a80324/v1alpha1/grafeas.json#L1301

**Comment by R2wenD2** [comment]
Per https://github.com/Grafeas/Grafeas/issues/50 I'm going to migrate this to proto w/ GRPC (I hope to have the initial proto ready for review today). So this shouldn't be an issue going forward.
