### ISSUE TITLE
Kritis

### ISSUE THREAD

**Issue by dnascimento** [grafeas/grafeas#60]
Where is Kritis source code? I'm looking for the policy verification engine.

**Comment by R2wenD2** [comment]
@nenaddedic When will Kritis source code be available?

**Comment by sandraguo** [comment]
@dnascimento @R2wenD2 
Kritis doesn't currently have an open source implementation yet. We have a white-paper describing the high level approach with Kritis that we'd love to hear your input. At the mean time, please fill in the interest [form](https://docs.google.com/forms/d/e/1FAIpQLSdr8kDTkAkml5f9TW_kzz06C0s0QuV_sWYzHC7NM90F5CZ2bQ/viewform) and we will let you know when we have any updates.

**Comment by dnascimento** [comment]
Happy to provide that input, can you share the white-paper with me?

**Comment by sandraguo** [comment]
@dnascimento It is checked in here: https://github.com/Grafeas/Grafeas/blob/master/case-studies/binary-authorization.md

**Comment by hpejustin** [comment]
@dnascimento i known very well of kubernetes scheduler source code, the design is very similar with policy verification engine. i think we can think about it.

**Comment by tejal29** [comment]
The kritis source code is github.com/grafeas/kritis
