### ISSUE TITLE
New release for grafeas?

### ISSUE THREAD

**Issue by chitrangpatel** [grafeas/grafeas#601]
We currently use `grafeas v0.2.2` in [Tektoncd/Chains](https://github.com/tektoncd/chains). There have been 31 additional comments since that release including things like support for SLSA v1.0 predicate. 

We are able to produce SLSAv1.0 provenance in Tektoncd/Chains and would like to start storing the occurrences using the Grafeas API. Would we be able to do that with version `0.2.2` (from April)? Or do we need changes from since then (possibly in another release)? When is the next release for Grafeas planned for?

cc @chuangw6, @sherzberg-1

**Comment by chuangw6** [comment]
@wkozlik any plan to cut a release for this new support? Thanks!

**Comment by wkozlik** [comment]
I will make a new release this week.

**Comment by chuangw6** [comment]
Sounds great. Thanks @wkozlik !

**Comment by chuangw6** [comment]
https://github.com/grafeas/grafeas/releases/tag/v0.2.3 Thanks @wkozlik !
