### ISSUE TITLE
Use golang/dep for managing the vendor tree

### ISSUE THREAD

**Issue by R2wenD2** [grafeas/grafeas#62]
golang dep is the new/recommended way to handle deps.

**Comment by sdboyer** [comment]
i'm happy to lend a hand on this if needed, btw 😄

**Comment by sdboyer** [comment]
though, worth noting that we just merged `govendor` support a couple days ago. when we roll the next release, `v0.4.0`, conversion might/should hopefully be as simple as a `dep init`.

**Comment by R2wenD2** [comment]
@sdboyer Thanks! when do you expect v.0.4.0 to roll? I don't think there's a particular rush here, so we can wait.

**Comment by sdboyer** [comment]
cool cool 👍 

we're basically just polishing up golang/dep#943, so that `dep prune` will no longer need to be a thing. milestone is here: https://github.com/golang/dep/milestone/4

in other words, it's been "this week" for a few weeks now. 😄

**Comment by vbatts** [comment]
Oh cool. I'm all for "simpler".

**Comment by sdboyer** [comment]
errr, whoops, i misremembered that issue number - much as i love 933, the relevant issue is golang/dep#944 😄
