### ISSUE TITLE
grafeas.json isn't compatible with Swagger tools

### ISSUE THREAD

**Issue by allisterb** [Grafeas/Grafeas#63]
So far I've been unable to use the Swagger JSON spec at https://raw.githubusercontent.com/Grafeas/Grafeas/master/v1alpha1/grafeas.json to generate any client or server code for the Grafeas API.

Using swagger-ui gives an error: "Parser error on line 523 duplicated mapping key"

Using NSwag, a .NET code generator for Swagger specs, throws a deserialization exception: "Requested value 'tags' was not found."

From what I can tell it seems that the current JSON spec for Grafeas doesn't follow the Swagger schema. Trying to validate grafeas.json at https://www.jsonschemavalidator.net/ throws many errors about the 'id' property not being part of the schema e.g this fragment:

```
"definitions": {
    "Occurrence": {
      "id": "Occurrence",
```

doesn't appear to be valid Swagger JSON.

**Comment by R2wenD2** [comment]
I'm planning to remove the json in the next few days. Please use the protocol buffer instead. Thanks
