### ISSUE TITLE
Split up the grafeas.proto file.

### ISSUE THREAD

**Issue by vtsao** [grafeas/grafeas#69]
Split this file up like we do internally, right now it's massive and hard to sync from internal protos.

**Comment by vbatts** [comment]
good stuff. Is this something you are going to work on?

**Comment by vtsao** [comment]
Yup.

**Comment by vbatts** [comment]
cool

**Comment by R2wenD2** [comment]
This was done for v1beta1 @vtsao I think we can close this, wdyt?
