### ISSUE TITLE
Replace references to Google Cloud Storage

### ISSUE THREAD

**Issue by furuholm** [grafeas/grafeas#73]
The grafeas schema contains several references to Google Cloud Storage (samples/server/go-server/api/storage_source.go, samples/server/go-server/api/build_provenance.go). I think these fields should be replaced by something less specific.

**Comment by hpejustin** [comment]
Yeah, we are on the same page. File "samples/server/go-server/api/source.go" contains ArtifactStorageSource field, type of this field is StorageSource(only references to Google Cloud Storage). This is also too specific, other storage should be supported too.

**Comment by R2wenD2** [comment]
I'm open to proposals for: 
- Additional storage sources
- A scheme for a more generic storage source.

It's probably easier to reference the [proto](https://github.com/Grafeas/Grafeas/blob/master/v1alpha1/proto/grafeas.proto) when making proposals/reasoning about this.

**Comment by furuholm** [comment]
There should probably be a generic "url source" at least. Can Google Cloud Storage objects be represented with urls?

**Comment by furuholm** [comment]
Got to think of this issue as I was reading through the v1beta1 protos. Seems to me that cloud storage could be referenced using a url 

    gs://[BUCKET_NAME]/[OBJECT_NAME1]#[GENERATION_NUMBER1]

Source: https://cloud.google.com/storage/docs/using-object-versioning
Maybe v1beta1 is a good time to make this change?

**Comment by R2wenD2** [comment]
Lets add the generic "url source" I need to follow up with folks who are using the structured Google Cloud Storage fields before we can completely remove it.

**Comment by furuholm** [comment]
Fixed by #161
