### ISSUE TITLE
Project listing API

### ISSUE THREAD

**Issue by furuholm** [Grafeas/Grafeas#74]
I am planning to write a simple frontend for Grafeas. To do this I need to list projects but as far as I can see there is no API for this (right?)

If it is agreed upon that this is a good idea I would be willing to submit a PR for this.

**Comment by antweiss** [comment]
I agree this is a necessity.

**Comment by hpejustin** [comment]
@furuholm i think it is a good idea, need any help, just feel free to let me know.

**Comment by furuholm** [comment]
A question: should `Project` be its own type in the schema with a single field `ProjectId`? The alternative would be to represent projectId as a string.

**Comment by R2wenD2** [comment]
@furuholm We can create a separate service (in a separate proto) for projects, we need the whole CRUD for them, (although update probably won't be needed as its just string field). Grafeas only references the string - so this can start out super simple, and as we dig deeper in to ACLs we'll likely need to expand.

**Comment by R2wenD2** [comment]
Also, please see https://github.com/Grafeas/Grafeas/issues/40 which I believe this issue is a duplicate of.

**Comment by furuholm** [comment]
Started working on this earlier today and started super simple by parsing projects from existing notes and occurrences (see https://github.com/furuholm/Grafeas/commit/ec083e56908fbbac75bfb67154b88787a65dbea2). But if we go full CRUD on this (as I suspect we will as you already created an issue for this 😄) then this is a duplicate of #40. 

Closing this in favor of #40.
