### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by kudvanpk** [grafeas/grafeas#78]
At the KubeCon BoF there were three hooks discussed to the core metadata DB (Grafeas core), 
1. Producers  (for each artifact, metadata in different formats, from different toolss/sources)
2. Consumers (Analysis, prioritization, machine learning across metadata/artifact types)
      Tooling to perform analysis across artifacts. Combine queried information to create risk scores. For example image reputation/signing, package importance/network accessible/utilization (e.g. openssl vs tar), history of packages risk (e.g. OpenSSL), CVSS score, runtime information etc.
3. Admission Control (based on authorization, policy etc)

Proposal for 2. Tooling across artifacts/risk assessment to be submitted soon

**Comment by R2wenD2** [comment]
At least some of the tooling that we discussed may be blocked by https://github.com/Grafeas/Grafeas/issues/29. I'm working out how to best get open source list filtering into Grafeas, you should see progress there in the coming weeks. 

@kudvanpk Are you planning to write tooling? I'm not sure if anyone else is actively working on tools at this point.

**Comment by vbatts** [comment]
wouldn't some of these fall into the kritis use-case?

**Comment by aysylu** [comment]
Some of the context was lost, so it's not clear whether there's a specific proposal or question that needs to be addressed here. Closing this due to the lack of activity, but please feel free to re-open with clarifications or open a new dedicated issue.
