### ISSUE TITLE
Add database storage backend

### ISSUE THREAD

**Issue by furuholm** [grafeas/grafeas#84]
A database will be required to run Grafeas in anything but development mode.

**Comment by R2wenD2** [comment]
We would get a lot of flexibility for querying various metadata by using Elastic (https://github.com/elastic/elasticsearch) in development go client: https://github.com/elastic/go-elasticsearch

**Comment by furuholm** [comment]
Sounds like a good idea.

Any ideas on type of database? Normalizating all those nested fields will be messy and require lots of join ops during querying so if we go the SQL route (which seems reasonable to me) it’s probably a good idea to store some of the data in serialized form.

**Comment by R2wenD2** [comment]
PostgreSQL would be a good option, as we could use the built in [text search] (https://www.postgresql.org/docs/current/static/textsearch-features.html) if we parse incoming protos into documents. 

We could then store fields required for get/indexing as well as the bytes of the proto, while indexing the proto into a ts_vector in our table.

**Comment by furuholm** [comment]
Maybe the [JSON support in PostgreSQL](https://www.postgresql.org/docs/9.6/static/datatype-json.html) could be of interest as well? I have not used it myself (and I'm not sure how it interacts with the text search features) so it would be interesting to hear what others have to say about it.

**Comment by furuholm** [comment]
Is the strategy to build a CEL compiler that builds postgresql text search queries? It seems to me that a CEL compiler for JSONB queries should be easier to write and get right than one for text strings as there is more structure in the data to leverage.

**Comment by furuholm** [comment]
Until the details have been settled, would a PR with a basic PostgreSQL implementation of the Storager interface be of interest or are there other plans for making this happen? If there is interest I could take this on.

I suggest we start simple with one table each for projects, notes, occurrences and operations. The tables only have to contain name and marshaled data to start with. Getting this and the infrastructure in place would set us up for continued work.

A couple of notes:
- Since there will be more than one type of storage there needs to be a way to select which one to use. I personally like how [Clair](https://github.com/coreos/clair) has strucutured its storage implementation by letting each storage implementation register itself using an init function (see [pgsql.go](https://github.com/coreos/clair/blob/master/database/pgsql/pgsql.go) for an example). I suggest we do something similar.
- There needs to be a config file to configure the database (and other things). I suggest a YAML file.
- I think we could postpone support for database migrations for now.

**Comment by R2wenD2** [comment]
You can get started with implementing the Storager interface with PostgrSQL JSON support in PostgreSQL looks like a good option for us (I also haven't used it though). We can hold off on adding indexing features until the CEL parser is available. 

I think having 1 table for each projects, notes, occurrences, and operations is the right way to go.

DB config as a yaml sounds good. 

Do you anticipate using more than one storage in the same running server? Otherwise, I think we could just have main handle db system and provide flags to indicate which to startup with.

**Comment by furuholm** [comment]
Agree on the storage init. Will try to make something simple. If we need pluggable storage at some later point we can revisit...

**Comment by furuholm** [comment]
I have implemented support for Postgres in a branch but it builds on the project-crud branch so I'll wait with creating a PR until project-crud has been merged.

A couple of notes:
- I have gathered all test cases in a [new file](https://github.com/combient/Grafeas/blob/postgres-storage/samples/server/go-server/api/server/storage/storager_test.go) to avoid test duplication. The test cases have been moved to subtests. [memstore_test.go](https://github.com/combient/Grafeas/blob/postgres-storage/samples/server/go-server/api/server/storage/memstore_test.go) and [pgsqlstore_test.go](https://github.com/combient/Grafeas/blob/postgres-storage/samples/server/go-server/api/server/storage/pgsqlstore_test.go) calls a single function to run all tests. Is there a better way to do this?
- I skipped the relation between projects and the other entities in the db as we forsee projects being placed in a different service.

Sidenote: I'm not sure why the Storager interface is placed in the server-go package. I think it belongs in the storage package and should be renamed Datastore, Store or something like that. Any thoughts on this?

**Comment by furuholm** [comment]
The PostgreSQL unit tests needs a running PostgreSQL server to run. Not sure how to best handle this. Ideas?

**Comment by vbatts** [comment]
@furuholm a kubernetes config to run a postgres instance and a test container to run against it. 
This is becoming a pattern, but seems to be home grown by each project. 
An e2e to be run. The next step is having it run in CI for pull requests...

**Comment by furuholm** [comment]
@vbatts True. I think docker-compose probably has a lower barrier though. Also seems like it's supported by CircleCI. https://circleci.com/docs/2.0/docker-compose/

(Sidenote: Either way there should be kubernetes configs. I deploy Grafeas using a helm chart that I created. Maybe that should be added as well.)

**Comment by vbatts** [comment]
I imagine groups like circleci will add kubernetes support before long

**Comment by R2wenD2** [comment]
Can you point me to the db schema proposal?

Re: server-go package, this is because we'd like to work toward a functioning reference implementation outside of the samples directory :)

**Comment by furuholm** [comment]
The db schema can be found here: https://github.com/combient/Grafeas/blob/postgres-storage/samples/server/go-server/api/server/storage/queries.go

**Comment by R2wenD2** [comment]
Are the "id" fields in note, occurrence and operation referring to projectids? I don't think we need a foreign key, but we'll want to be able to namespace by project. 

Also, I have a slight preference for notes, occurrences, and operations as table names.

**Comment by furuholm** [comment]
The id fields are not referring to projectids. The only foreign key is occurrence.note_id.

We could add separate project name columns to notes, occurrences and operations, but I chose to search the beginning of the names instead. As I understand this should be quite performant and we avoid data duplication. If you want I can add a project column though.

Tabs vs spaces. Pluralized table names or not :) I will add s:s to the tables 😄

**Comment by R2wenD2** [comment]
For the note reference by projects/foo/occurrences/bar, I think it would make sense to have a column project_name that contains foo and have another column note_name which contains bar. 

The foreign key to notes from occurrences could then be (note_project_id, note_id) which allows us to more easily list notes by project. WDYT?

**Comment by furuholm** [comment]
I'm not sure I understand the second paragraph (is note_id the same as note.id and or is it the same as note_name or something else? What is note_project_id). Maybe you could share a schema draft?
