### ISSUE TITLE
Lowercase Grafeas repo and org

### ISSUE THREAD

**Issue by furuholm** [Grafeas/grafeas#93]
Go get is case insensitive while glide is not. This causes issues when using grafeas or its sibling repos as a dependency. I think the right thing to do is to change the github org and repo to lowercase (Grafeas/Grafeas -> grafeas/grafeas). While this may cause problems it won't be easier down the line. 

BTW: Grafeas is [not the only package that have done this this](https://github.com/sirupsen/logrus/pull/384)

**Comment by vbatts** [comment]
+1
I already clone it lowercase, but it does cause a glitch every so often.

**Comment by R2wenD2** [comment]
I've run into this myself too. It is done, sorry about the capital inconvenience.
