### ISSUE TITLE
swagger documentation has errors

### ISSUE THREAD

**Issue by doomsbuster** [grafeas/grafeas#95]
When i point swagger to the grafeas.json in v1alpha it throws parsing errors on line 523

```
Errors
Hide
Parser error on line 523
duplicated mapping key
```

Pointed at `https://raw.githubusercontent.com/Grafeas/Grafeas/master/v1alpha1/grafeas.json`

**Comment by vbatts** [comment]
can you check against https://github.com/Grafeas/Grafeas/blob/master/v1alpha1/proto/grafeas.swagger.json

as the other one will be going away soon.

**Comment by doomsbuster** [comment]
Thanks that worked. I fired up the sample server from the master branch. That does not seem to have any API endpoints that you have in the newer version (esp. project creation API's). Is there a different branch where I can try the sample server and all available API's. Without a project, I am not sure what to do with the sample server.

I did explore tiny bit more on the current one, the following API operation is defined twice resulting in the duplicate key error. I can submit a pull request if you like.

```
    "/v1alpha1/projects/{projectsId}/operations": {
      "get": {
        "tags": [
          "grafeas"
        ],
        "operationId": "ListOperations",
        "description": "Lists all operations for a given project.",
        "parameters": [
          {
            "name": "projectsId",
            "description": "Part of `parent`. This field contains the projectId for example:\n\"project\/{project_id}",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "filter",
            "description": "The filter expression.",
            "in": "query",
            "type": "string"
          },
          {
            "name": "pageSize",
            "description": "Number of operations to return in the list.",
            "in": "query",
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "pageToken",
            "description": "Token to provide to skip to a particular spot in the list.",
            "in": "query",
            "type": "string"
          }
        ],
        "responses": {
          "default": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/ListOperationsResponse"
            }
          }
        }
      }
    },
```

**Comment by R2wenD2** [comment]
https://github.com/Grafeas/Grafeas/blob/master/v1alpha1/proto/grafeas.swagger.json is the way to go, its not clear to me from your comment whether you're seeing issues there or in the now deleted swagger file?

**Comment by doomsbuster** [comment]
The URL @vbatts provided works in that swagger UI no longer throws the `duplicate key mapping` error. 

When you look at [that API spec](https://github.com/Grafeas/Grafeas/blob/master/v1alpha1/proto/grafeas.swagger.json), there is a `/v1alpha1/{name}` endpoint that should create a new project for me.

![image](https://user-images.githubusercontent.com/4811092/35073534-4eee9676-fbb7-11e7-81bb-bb5ec82b1246.png)

**The Problem:**
I cloned this repo and started up the sample server `go run main.go`. It started of the API server on `localhost:10000`. Then I wrote up a [barebones test](https://gist.github.com/doomsbuster/836cbdef8f78503aa45680025e5edb1a) that would get a list of projects and create a new project in Grafeas.

I am receiving a 404 for the endpoint that should have created a new project in Grafeas.

```
Spec started
{ projects: [], nextPageToken: '' }

  Grafeas API Spec Test
    ✓ should return a list of all projects
Error: expected 200 "OK", got 404 "Not Found"
    at Test._assertStatus (/Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/supertest/lib/test.js:266:12)
    at Test._assertFunction (/Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/supertest/lib/test.js:281:11)
    at Test.assert (/Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/supertest/lib/test.js:171:18)
    at assert (/Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/supertest/lib/test.js:131:12)
    at /Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/supertest/lib/test.js:128:5
    at Test.Request.callback (/Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/superagent/lib/node/index.js:715:3)
    at IncomingMessage.parser (/Users/doomsbuster/Documents/coding/sublime/grafeas-client/node_modules/superagent/lib/node/index.js:903:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    ✓ should create a new project

Executed 2 of 2 specs SUCCESS in 0.037 sec.
```

**Comment by furuholm** [comment]
Your test references `/v1alpha1/mrdoomsbuster`. Try `/v1alpha1/projects/mrdoomsbuster` instead. 

It's easy to see how you came to this conclusion given the Swagger documentation though. 

@R2wenD2: If Swagger is the canonical documentation for the REST API, maybe the url parsing logic should be revisited to use project/note/occurrence/operation id:s instead of passing the full path?

**Comment by doomsbuster** [comment]
@furuholm that worked, i think the swagger documentation needs some updating. I can offer up to help you write some good technical and getting started documentation around this.

**Comment by R2wenD2** [comment]
While swagger should be an option, I don't think it should be the canonical documentation - as we made a choice to go with grpc. I think the proto annotations that are generating the swagger just need to be fixed. I can TAL at this today or tomorrow (I'm dealing with some production issues right now, but I'll get to it ASAP).

**Comment by doomsbuster** [comment]
I am going to run a few more tests on the API to make sure the key workflows we are looking to utilize function as advertised. If we can keep this open, till that time, it will be good.

**Comment by R2wenD2** [comment]
I'll definitely keep this open to track fixing the proto annotations too :)

Feel free to send any PRs to help with the documentation too :)

**Comment by furuholm** [comment]
@R2wenD2 Even if Swagger is not the canonical docs, I still think that it would make more sense to skip the name string entirely and switch to using project/note/occurrence/operation names as separate arguments, even more so when gRPC has been introduced. That this would also improve Swagger would be a nice side effect.

**Comment by furuholm** [comment]
Wrote some client code today and I really think the API needs to be cleaned up.

I would suggest the following:
- Remove the notion of note/occurrence/operation name from the codebase and only use what is now called pID, nID and oIDs instead (although what is called id today should maybe be called name)
- Use ids instead of the stringly typed name string in the API. E.g. instead of `name: projects/myproj/notes/mynote` you would get `project: myproj` and `id: mynote` (project could also be called parent, and id could also be called name, note_id or note_name).

**Comment by R2wenD2** [comment]
That all sounds reasonable, we just need to parse the stringly typed name earlier and start using that to hand around in the API code. 

We should keep the proto as is though, as these are the restful paths to access objects.

**Comment by furuholm** [comment]
I realise that you are probably right about the proto, but just so I can let this go: why should the proto use the restful paths? To me it makes more sense to let the rest API adapt itself to the protobuf:

Instead of
```
  rpc GetNote(GetNoteRequest) returns (Note) {
    option (google.api.http) = {
      get: "/v1alpha1/{name=projects/*/notes/*}"
    };
  }
```
we would get something like
```
  rpc GetNote(GetNoteRequest) returns (Note) {
    option (google.api.http) = {
      get: "/v1alpha1/projects/{project_name=*}/notes/{note_name=*}"
    };
  }
```
I don't know if that is even a valid specification, but hopefully it's clear enough to communicate the idea :)

**Comment by R2wenD2** [comment]
We're adhering to the guidelines here: https://cloud.google.com/apis/design/standard_methods

**Comment by furuholm** [comment]
Awesome...thanks :)

**Comment by mykter** [comment]
In the v1alpha1 swagger output, all of the GrafeasProjects methods have picked up documentation from other methods:

```
"/v1alpha1/projects": {
      "get": {
        "summary": "Deletes the given `Occurrence` from the system. Use this when\nan `Occurrence` is no longer applicable for the given resource.",
...
      "post": {
        "summary": "Returns the requested `Occurrence`.",
        "operationId": "CreateProject",
...
"/v1alpha1/{name}": {
      "get": {
        "summary": "Lists active `Occurrences` for a given project matching the filters.",
        "operationId": "GetProject",
...
      "delete": {
        "summary": "Creates a new `Occurrence`. Use this method to create `Occurrences`\nfor a resource.",
        "operationId": "DeleteProject",
```

**Comment by vtsao** [comment]
Yeah there is a known issue with how protoc generates Swagger spec from protos when using the google.api.http annotations. Google API HTTP annotations support pattern matching like "/v1beta1/{name=projects/*/occurrences/*}" that the Swagger spec doesn't support. So the generated Swagger JSON spec isn't 100% correct and then there are also documentation issues.

We're looking into how to get around this right now.

Also the Swagger spec we generate right now is only used to generate Swagger client libraries for Grafeas. How important is it for people to use Swagger client libraries versus the protoc generated bindings? E.g., https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/grafeas_go_proto/grafeas.pb.go

**Comment by abu-abraham** [comment]
Also, I found certain issues with the create note functionality. Create note requires note_id as a query parm which is not in accordance with the swagger documentation for v1beta1. 

Another issue I found is the different casing used in the project. According to swagger-docs and protos, we use snake_casing, however, grafeas internally use camelCasing and returns objects accordingly.

**Comment by vtsao** [comment]
Root issue for this is captured in https://github.com/grafeas/grafeas/issues/379.
